# Site settings
title: Fernando Gomez - A blog about coding
email: info@fhergomez.com
description: A blog about my favorite coding sites and tutorials.
url: "http://www.fhergomez.com/blog" # the base hostname & protocol for your site
twitter_username: fhergomez70
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"

# Build settings
 github: [metadata]
 markdown: kramdown
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-watch
   - jekyll-assets
   - rake
permalink: /:title

# Default settings
defaults:
    -
      scope:
        path: "" # an empty string here means all files in the project
        type: "posts" # previously "post" in jekyll 2.2.
      values:
        author: Fernando Gomez
        layout: "post"
        category: conferences
        comments: true
    -
      scope:
        path: "" # an empty string here means all files in the project
        type: "pages" # previously "post" in jekyll 2.2.
      values:
        layout: "page"
    -
      scope:
        path: "" # an empty string here means all files in the project
        type: "drafts" # previously `post` in Jekyll 2.2.
      values:
        author: Jonnie
        category: conferences
        layout: "post"