# Site settings
title: Fernando Gomez - A blog about coding
email: info@fhergomez.com
description: A blog about my favorite coding sites and tutorials.
url: "http://www.fhergomez.com/blog" # the base hostname & protocol for your site
twitter_username: fhergomez70

# Build settings
markdown: kramdown
permalink: /:title